<!-- Message Priorities subsubtab  --->

<?php
// Function to place a slider with the following:
// $label is the title to be displayed
// $name is the html name of the control
// $value is the value assigned to the slider
// $tooltip is the tooltip text to display  -- this does not currently work - don't know why
function DrawSlider($label, $name, $value, $tooltip)
{
	ob_start(); ?>
	<div class="row">
		<span class="label2" >
			<div class="slider-row"></div>
			<div class="slider-row"><?php echo $label; ?></div>
		</span>
		<span class="formw-slider">
			<div class="slider-row">
				<div class="slider-label-left slider-label" >WiFi/Ethernet</div>
				<div class="slider-label-center slider-label">Cell</div>
				<div class="slider-label-right slider-label">Iridium*</div>
			</div>
			<div class="slider-row">
				<?php
					echo '<input type="range" name='.$name.' min="1" max="3" step="1" value="'.$value.'" title="'.$tooltip.'"/>';
				?>
			</div>
		</span>
	</div>
	<?php
		$output = ob_get_contents();
		ob_end_clean();
		echo $output	;
} ?>

<script type="text/javascript" src="/js/message_priority.js"></script>
<form id="msgpriorityCheck" method="post" action="/inc/message_priority_processor.php">
	<div>
		<!-- Header -->
		<div class="inversetab">Message Priority</div>
		<!--- <a href="/TL3000_HTML5/Default_CSH.htm#COMPORTS" TARGET="_blank"><img src="/images/help.png" alt="help" border="0" ></a> -->
		<br/>
			<span>The message priority that is selected represents the highest level of communications that will be attempted for that message type.<br><br></span>
			<span>If <b>WiFi/Ethernet</b> is selected the message will not be sent over either Cell or Iridium.<br><br></span>
			<span>If <b>Cell</b> is selected the message will be sent over either WiFi/Ethernet if they are available or Cell but never Iridum.<br><br></span>
			<span>If <b>Iridium</b> is selected the message will be sent over either WiFi/Ethernet if they are available or Cell if it is available then finally tried over Iridum.<br></span>
	</div>
	<div id="msgprioritySection">
		<fieldset>
			<legend>General</legend>
			<?php
			 DrawSlider("CalAmp User Message", "MP_calamp_user_pri", $mp_calamp_user_pri, "Generic CalAmp user message") ;
			 DrawSlider("Check In","MP_ci_pri", $mp_ci_pri, "Check in to monitoring center");
			 DrawSlider("Check Out","MP_co_pri", $mp_co_pri, "Check out from monitoring center");
//		 // DrawSlider("Ping","MP_ping_pri", $mp_ping_pri, "");
			?>
			<div class="spacer">&nbsp;</div>
		</fieldset>
		<div class="spacer">&nbsp;</div>
		<fieldset>
			<legend>Device Status</legend>
			<?php
			 DrawSlider("Heartbeat", "MP_heartbeat_pri", $mp_heartbeat_pri, "Regular heartbeat message") ;
			 DrawSlider("Critical Battery","MP_crit_batt_pri", $mp_crit_batt_pri, "Message sent when voltage falls below critical level");
			 DrawSlider("Low Battery","MP_low_batt_pri", $mp_low_batt_pri, "Message sent when voltage falls below cutoff - system will then shut down");
			 DrawSlider("Sensor Change","MP_sensor_pri", $mp_sensor_pri, "Message sent when any input changes");
			?>
			<div class="spacer">&nbsp;</div>
		</fieldset>
		<div class="spacer">&nbsp;</div>
		<fieldset>
			<legend>Position Update</legend>
			<?php
			 DrawSlider("Scheduled Message","MP_sched_msg_pri", $mp_sched_msg_pri, "All messages generated by the Position Update settings");
//			 DrawSlider("Power On","MP_power_on_pri", $mp_power_on_pri, "");
//			 DrawSlider("Power Off","MP_power_off_pri", $mp_power_off_pri, "");
			 DrawSlider("Start","MP_start_pri", $mp_start_pri, "Message sent when vehicle starts moving");
			 DrawSlider("Stop","MP_stop_pri", $mp_stop_pri, "Message sent when vehicle stops moving");
			 DrawSlider("Ignition On","MP_ignition_on_pri", $mp_ignition_on_pri, "Message sent when vehicle ignition comes on");
			 DrawSlider("Ignition Off","MP_ignition_off_pri", $mp_ignition_off_pri, "Message sent when vehicle ignition goes off");
//			 DrawSlider("Engine On","MP_engine_on_pri", $mp_engine_on_pri, "");
//			 DrawSlider("Engine Off","MP_engine_off_pri", $mp_engine_off_pri, "");
			?>
			<div class="spacer">&nbsp;</div>
		</fieldset>
		<div class="spacer">&nbsp;</div>
		<fieldset>
			<legend>J1939</legend>
			<?php
			 DrawSlider("Periodic Message","MP_j1939_periodic_pri", $mp_j1939_periodic_pri, "J1939 data message sent at regular intervals");
			 DrawSlider("Exceedence Message","MP_j1939_exceed_pri", $mp_j1939_exceed_pri, "J1939 exceedence message sent when exceedence occurs");
			 DrawSlider("Fault Message","MP_j1939_fault_pri", $mp_j1939_fault_pri, "J1939 fault message sent when fault occurs");
			?>
			<div class="spacer">&nbsp;</div>
		</fieldset>
		<div class="spacer">&nbsp;</div>
		<fieldset>
			<legend>Modbus</legend>
			<?php
			 DrawSlider("Periodic Message","MP_modbus_periodic_pri", $mp_modbus_periodic_pri, "Modbus data message sent at regular intervals");
			 DrawSlider("Exceedence Message","MP_modbus_exceed_pri", $mp_modbus_exceed_pri, "Modbus exceedence message sent when exceedence occurs");
			 DrawSlider("Fault Message","MP_modbus_fault_pri", $mp_modbus_fault_pri, "Modbus fault message sent when fault occurs");
			?>
			<div class="spacer">&nbsp;</div>
		</fieldset>
		<div class="spacer">&nbsp;</div>
<!--
		<fieldset>
			<legend>Driver Behaviour</legend>
			<?php
//			 DrawSlider("Driver Status","MP_driver_status_pri", $mp_driver_status_pri, "");
//			 DrawSlider("Acceleration","MP_acceleration_pri", $mp_acceleration_pri, "");
//			 DrawSlider("Acceleration OK","MP_accel_ok_pri", $mp_accel_ok_pri, "");
//			 DrawSlider("Deceleration OK","MP_decel_ok_pri", $mp_decel_ok_pri, "");
//			 DrawSlider("Speed Acceptable","MP_speed_ok_pri", $mp_speed_ok_pri, "");
//			 DrawSlider("Speed Exceeded","MP_speed_exceed_pri", $mp_speed_exceed_pri, "");
			?>
			<div class="spacer">&nbsp;</div>
		</fieldset>
-->
	</div>
	<br />
	<div class="spacer">&nbsp;</div>
	<?php
	if(hasSubmitAccess())
	{
	?>
		<div class="row">
			<span class="formw2">
				<button type="submit" class="button2-link">Save</button>&nbsp;
				<button type="reset" class="button3-link">Cancel</button>&nbsp;
				<!--button class="button4-link">Sync</button>-->
				<br/>
			</span>
		</div>
	<?php
	}
	?>
</form>
