/*=================================================================================================

	LensMsg - Base class for reading and writing messages to the LENS
		  radio.  This is a virtual base class so it cannot be instantiated on its own.

	The messages are defined in "Whisper Host Interface Document - Gateway.doc" 
==================================================================================================*/

class LensMsg
{
private:
	unsigned char m_Type;  // the hex value of the message type - defined in constructor of derived class
	unsigned char m_Length; // length of the outgoing message - valus is fixed for some messages.
	int m_Error;  // error codes generated by encoding and decoding. If functions return false then Error() will be non-0

public:
	LensMsg()m_Error(0), m_Type(0) {};
	virtual ~LensMsg(){};

	virtual bool Encode(unsigned char *msg) = 0;  // encode a byte stream, msg will include framing
	virtual bool Decode(unsigned char *msg) = 0;  // decode a byte stream, msg includes framing

	int Error() const {return m_Error;};
};

